### PR TITLE
implement jimp backend

### PR DESCRIPTION
**Pull request by ramirezd42**
This resolves https://github.com/punkave/uploadfs/issues/13
Added a jimp-based backend.

I'm not sure what node version(s) uploadfs and apostrophe are targeting. All tests pass and it works in apostrophe with a node version as low as 6.11.0 (the current LTS version).

I'd love some feedback. If there's interest in merging, I could look at updating the tests to run with this backend as well. For now, I'm just modifying the test script in my working copy to specify the jimp backend:

```
// test.js
var localOptions = { storage: 'local', uploadsPath: __dirname + '/test', uploadsUrl: 'http://localhost:3000/test', image: 'jimp' }; 
```

### CODE REVIEW

**Comment by ramirezd42** [comment]
Thanks for the feedback!

I addressed your concerns in the latest commit. Also added wording to the README mentioning the lack of animated GIF support.

**Comment by boutell** [comment]
Thank you Dave! This has been merged and published as 1.4.0. Jimp is now the fallback backend if imagemagick and imagecrunch are not found, removing an obstacle to getting started with Apostrophe.

**Comment by EddieOne** [comment]
Just need to update the readme now. I think many will prefer Jimp over ImageMagick.

**Comment by boutell** [comment]
The README does mention jimp; did I miss something?

**Comment by EddieOne** [comment]
I don't know how strong the relation between this repo and the main one are. Would be nice to mention Jimp here I think. https://github.com/apostrophecms/apostrophe

**Pull request merged**
